CREATE TABLE IF NOT EXISTS files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parentId INT DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    size BIGINT DEFAULT NULL,
    mimetype VARCHAR(100) DEFAULT NULL,
    objectType ENUM('FILE', 'FOLDER') NOT NULL DEFAULT 'FILE',
    status ENUM('ACTIVE', 'SOFT_DELETED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
    storageKey VARCHAR(512) DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_parent_id
        FOREIGN KEY (parentId) 
        REFERENCES files(id)
        ON DELETE CASCADE
);